### ISSUE TITLE
Proxy generator emits different module layout in Debug and Release

### ISSUE THREAD

**Issue by einari** [Cratis/ApplicationModel#2547]
The proxy generator emits different TypeScript for the same C# source depending on the build configuration, and the two shapes are incompatible with each other.

For an enum declared in its own C# file, alongside other types in the same folder:

- A **Debug** build emits the enum as its own TypeScript module and re-exports it from the folder barrel.
- A **Release** build folds the enum back into the module generated for the neighbouring type and **deletes** the separate file.

Either shape works on its own. The problem is that they disagree, so whichever configuration was built last rewrites the other's output, and any hand-written module that imports the enum directly breaks:

```
error TS2305: Module '"./Status"' has no exported member 'SliceStatus'.
```

Committing one shape does not settle it. Committing the Debug shape means CI, which builds Release to produce images, deletes the file out from under the imports and fails the frontend compile. Committing the Release shape means every local Debug build re-splits it and breaks the same imports again. There is no state of the repository that satisfies both.

## Reproducing

In a Cratis application with an enum in its own file next to a `[Command]`/`[ReadModel]` in the same folder:

1. `dotnet build -c Debug` - the enum is emitted as `<Enum>.ts`, and the barrel re-exports it.
2. `dotnet build -c Release` - `<Enum>.ts` is deleted and the enum reappears inside the neighbouring module.

Observed in Cratis Studio with `SliceStatus` (`Source/Core/Projects/Applications/Domains/EventModels/Modules/Features/Slices/Status/`), where `SliceStatus.cs` declares `public enum SliceStatus` beside `Status.cs`.

## Why it matters beyond the churn

Imports from *outside* the folder are unaffected, because there the folder barrel resolves and re-exports whichever shape was generated. Only modules inside the folder, importing the sibling directly, break - which makes it look intermittent and local to whoever built last, rather than a generator inconsistency.

The generated files carry `// @generated by Cratis ... DO NOT EDIT`, so there is nothing to fix at the point of the error.

## Expected

One shape, whichever is preferred, produced identically in every configuration. Emitting a type declared in its own C# file into its own module seems the more predictable of the two, since it mirrors the source layout.

**Comment by einari** [comment]
Fixed in #2548.
